#!/bin/bash

#clone repo structure if it does not exist

REPOS="
gnuradio-companion-exe
gr-pothos
PothosCore
PothosAudio
PothosBlocks
PothosComms
PothosDemos
PothosFlow
PothosIIO
PothosJava
PothosOpenCL
PothosPlotters
PothosPython
PothosSoapy
PothosWidgets
PothosLiquidDSP
SoapyAirspy
SoapyAudio
SoapyBladeRF
SoapyHackRF
SoapyMultiSDR
SoapyOsmo
SoapyRedPitaya
SoapyRemote
SoapyRTLSDR
SoapySDR
SoapySDRPlay
SoapyUHD
"

ROOT=$1

if [[ -z "${ROOT}" ]]; then
    echo "Usage: $0 [root path]"
    exit -1
fi

echo "Cloning repos into ${ROOT}"

for REPO in $REPOS; do
    GIT_REPO=${ROOT}/${REPO}/
    GIT_URL=git@github.com:pothosware/${REPO}.git
    if [ ! -d "$GIT_REPO" ]; then
        echo "Cloning into $GIT_REPO"
        git clone $GIT_URL $GIT_REPO
    fi

    GIT_REPO=${ROOT}/docs/${REPO}.wiki/
    GIT_URL=git@github.com:pothosware/${REPO}.wiki.git
    if [ ! -d "$GIT_REPO" ]; then
        echo "Cloning into $GIT_REPO"
        git clone $GIT_URL $GIT_REPO
    fi
done

echo "Done!"
