#!/bin/bash

COMPONENTS="
gr-pothos
PothosAudio
PothosBlocks
PothosComms
PothosDemos
PothosFlow
PothosGPU
PothosIIO
PothosJava
PothosOpenCL
PothosPlotters
PothosPython
PothosSoapy
PothosWidgets
PothosLiquidDSP
"

ROOT=$1

if [[ -z "${ROOT}" ]]; then
    echo "Usage: $0 [root path]"
    exit -1
fi

for PREFIX in $COMPONENTS; do
    echo "======== ${PREFIX} ========"
    pushd ${ROOT}/docs/${PREFIX}.wiki
    git co master
    git pull origin master
    cp ../PothosCore.wiki/_Sidebar.rest .
    git add _Sidebar.rest
    git ci -am "updated sidebar"
    git push origin master
    popd
done
