#!/usr/bin/env python3

import os
import re
import sys
from pothos_scripts_common import *

SUBMODULES = [
'PothosAudio',
'PothosBlocks',
'PothosComms',
'PothosFlow',
'PothosPlotters',
'PothosPython',
'PothosSoapy',
'PothosWidgets',
]

def main():
    if len(sys.argv) != 3:
        print("Usage: %s [root path] [branch name]"%sys.argv[0])
        exit(-1)
    ROOT = sys.argv[1]
    BRANCH = sys.argv[2]

    #extract ABI
    for line in open(os.path.join(ROOT, 'PothosCore', 'include', 'Pothos', 'System', 'Version.hpp')).readlines():
        m = re.match('#define POTHOS_ABI_VERSION "(.+)"', line.strip())
        if m: libraryABI = m.groups()[0]
    assert(libraryABI)
    print("libraryABI=%s"%libraryABI)

    for SUBMODULE in SUBMODULES:

        debianDir = os.path.join(ROOT, SUBMODULE, 'debian')

        #switch to branch
        git_cmd(debianDir, 'checkout', BRANCH)
        git_cmd(debianDir, 'pull', 'origin', BRANCH)

        #rewrite files
        for resource in ['control', 'rules']:
            outputLines = list()
            outputFile = os.path.join(debianDir, resource)
            for line in open(outputFile).readlines():
                m = re.match('.*pothos(.+)-modules', line.strip())
                if m: line = line.replace('pothos'+m.groups()[0], 'pothos'+libraryABI)
                outputLines.append(line)
            open(outputFile, 'w').write(''.join(outputLines))

        #ensure rules is executable
        os.system('chmod +x %s'%os.path.join(debianDir, 'rules'))

        #move file for new ABI
        for fileName in os.listdir(debianDir):
            m = re.match('.*pothos(.+)-modules', fileName)
            if m:
                newFileName = fileName.replace('pothos'+m.groups()[0], 'pothos'+libraryABI)
                git_cmd(debianDir, 'mv', fileName, newFileName)

        #make the commit
        git_cmd(debianDir, 'commit', '-a', '-m', 'debian: updated to pothos%s module ABI'%libraryABI)
        git_cmd(debianDir, 'push', 'origin', BRANCH)

if __name__ == '__main__': main()
